### ISSUE TITLE
Nomenclatura na edição dos horários dos turnos

### ISSUE THREAD

**Issue by Pliavi** [BrainsWorking/WebHorario#18]
Verificar a utilização do javascript para a geração e remoção dos horários no cadastro de turno.
Na edição, se for adicionado um novo horário, o primeiro sempre receberá nome de aula 2, mesmo que na edição tenha, por exemplo, 5 horários.

Ex:
Aula 1
Aula 2 
Aula 3
Aula 4
Aula 5
**Aula 2**

Seria necessária uma forma de tornar essa variável (linha 6) dinâmica.
https://github.com/BrainsWorking/WebHorario/blob/master/public/js/cadastro_turno.js#L6

**Comment by cleytoncm** [comment]
Talvez se carregar a quantidade de aula que o turno tem e carregar esse valor na variável.

ai ficaria algo como:
var x =  {{ $qtdAula or '2' }} ;

Fica a minha sugestão.

P.S.: Não entendi porque você inicializou a variável x com 2.

**Comment by Pliavi** [comment]
Coloquei essa Issue só pra não esquecer mesmo, o script foi criado pelo @asasouza , o 2 está lá porque o primeiro valor já está no formulário, pois é sempre iniciado com um turno pra cadastrar (pro primeiro a mais não substituir o que está já no HTML).

**Comment by cleytoncm** [comment]
Estranhei você não ter pensado nisso, mas beleza então.

**Comment by Pliavi** [comment]
#22 @b13cd4f33a4eb247203219f8ed50b3df8f2d4965
