### ISSUE TITLE
Corrigir tamanho das imagens

### ISSUE THREAD

**Issue by Pliavi** [BrainsWorking/WebHorario#32]
Sempre evitem de utilizar imagens redimensionadas quando seu tamanho é muito diferente do que deseja utilizar, a menos que ela possa atingir todos os tamanhos (redimensionada dinamicamente).
Ex:
Logo do IFSP de tamanho 1495x414 sendo redimensionado para 250x69.

**Comment by asasouza** [comment]
Troca de imagem feita no PR #36
